Repository HYU-Kobot/Kobot, pull requests merged in 2023-02, with the labels that each got.

#7 Feat/6 change branch1to6
  frontend/src/views/dashboard/Default/CoinChartCard.js
  frontend/src/views/dashboard/Default/PopularCard.js
  frontend/src/views/dashboard/Default/index.js
Labels: FE, feat

#8 Revert "Feat/6 change branch1to6"
  frontend/src/views/dashboard/Default/CoinChartCard.js
  frontend/src/views/dashboard/Default/PopularCard.js
  frontend/src/views/dashboard/Default/index.js
Labels: FE, fix

#9 feat: react-tradingview-widget 사용으로 차트 구성 완료
  frontend/src/views/dashboard/Default/CoinChartCard.js
  frontend/src/views/dashboard/Default/index.js
Labels: FE, feat

#11 DB에 BTC 데이터 삽입
  backend/build.gradle
  backend/src/main/java/com/hyu/kobot/KobotApplication.java
  backend/src/main/java/com/hyu/kobot/domain/Candle.java
  backend/src/main/java/com/hyu/kobot/domain/Exchange.java
  backend/src/main/java/com/hyu/kobot/domain/Market.java
  backend/src/main/java/com/hyu/kobot/domain/TimeUnit.java
  backend/src/main/java/com/hyu/kobot/domain/repository/CandleRepository.java
  backend/src/test/java/com/hyu/kobot/AcceptanceTest.java
  backend/src/test/java/com/hyu/kobot/CandleAcceptanceTest.java
  backend/src/test/java/com/hyu/kobot/KobotApplicationTests.java
  backend/src/test/java/com/hyu/kobot/domain/ExchangeTest.java
  backend/src/test/java/com/hyu/kobot/domain/MarketTest.java
  backend/src/test/java/com/hyu/kobot/domain/TimeUnitTest.java
  backend/src/test/java/com/hyu/kobot/domain/repository/CandleRepositoryTest.java
  backend/src/test/resources/application.yml
Labels: BE, feat
